# GENERAL
RESULTS_DIR = "transcripts/"
TRANSCRIBE_LAST_N_ARTICLES = 25
WEBSITE = "https://duarteocarmo.com"
FEED_URL = f"{WEBSITE}/feed.xml"
LLM_PREPROCESSING_MODEL = "openai/gpt-5"
ENV_OPENAI_API_KEY = "OPENAI_API_KEY"
ENV_REBUILD_TRIGGER_URL = "REBUILD_TRIGGER_URL"
ENV_MODAL_IMAGE_BUILDER_VERSION = "MODAL_IMAGE_BUILDER_VERSION"
ENV_VLLM_WORKER_MULTIPROC_METHOD = "VLLM_WORKER_MULTIPROC_METHOD"
ENV_HF_XET_HIGH_PERFORMANCE = "HF_XET_HIGH_PERFORMANCE"
OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"

# MODAL
MODAL_GPU = "L40S"
MODAL_MAX_CONTAINERS = 1
MODAL_APP_NAME = "podcaster"
MODAL_PYTHON_VERSION = "3.10"
MODAL_REMOTE_REFERENCE_AUDIO_PATH = "/root/reference.wav"
MODAL_LOCAL_REFERENCE_AUDIO_PATH = "./data_raw/reference_enhanced.wav"
MODAL_IMAGE_BUILDER_VERSION = "2025.06"
VLLM_WORKER_MULTIPROC_METHOD = "spawn"
HF_XET_HIGH_PERFORMANCE = "1"

# QWEN TTS
QWEN_TTS_MODEL = "duarteocarmo/qwen_tts_finetune_0.6B_e10_l1e6"
QWEN_TTS_SPEAKER = "duarte"
QWEN_TTS_LANGUAGE = "English"
QWEN_TTS_MAX_CHARS_PER_CHUNK = 1000
QWEN_TTS_BATCH_SIZE = 1
QWEN_TTS_MAX_NEW_TOKENS = 2048
QWEN_TTS_CROSSFADE_MS = 50
QWEN_TTS_MODAL_IMAGE = "vllm/vllm-omni:v0.21.0rc1"
QWEN_TTS_VLLM_VERSION = "vllm==0.21.0"
QWEN_TTS_TASK_TYPE = "CustomVoice"

# STORAGE
BUCKET_NAME = "podcaster"
BUCKET_URL = (
    "https://cd7ef6e066027aea5df8b21d160a0431.r2.cloudflarestorage.com"
)
PUBLIC_BUCKET_URL = "https://r2.duarteocarmo.com"

# PODCAST
NAME = "Duarte O.Carmo"
PODCAST_CATEGORIES = [{"cat": "Technology"}]
PODCAST_DESCRIPTION = """
A podcast version of my personal website. All the episodes are generated from a text to speech model.
""".strip()
PODCAST_EXPLICIT = False
PODCAST_FEED_NAME = "podcast.xml"
PODCAST_IMAGE = f"{PUBLIC_BUCKET_URL}/cover.png"
PODCAST_NAME = f"{NAME}'s articles"
PODCAST_WEBSITE = WEBSITE
PODCAST_AUTHOR = {
    "name": NAME,
    "email": "me@duarteocarmo.com",
    "uri": PODCAST_WEBSITE,
}
